2019-05-07 11:13:23 Error: [MissingViewException] View file "Pages/adada.ctp" is missing.
Exception Attributes: array (
  'file' => 'Pages/adada.ctp',
)
Request URL: /cakephp/pages/adada
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Pages/adada')
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(960): View->render('adada', NULL)
#2 /var/www/html/cakephp/app/Controller/PagesController.php(68): Controller->render('adada')
#3 [internal function]: PagesController->display('adada')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PagesController), Array)
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 11:15:12 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:15:12 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:15:30 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:15:30 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:15:37 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:15:37 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:15:45 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:15:45 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of ParseError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(ParseError))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:37:50 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:37:50 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:38:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:38:41 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:39:29 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:39:29 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:40:10 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:40:10 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 11:41:21 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 11:41:21 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 13:03:52 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(TypeError))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 13:03:52 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 13:12:30 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-07 13:15:32 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-07 13:16:01 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-07 13:17:07 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-07 13:17:15 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 13:17:15 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 13:17:24 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-07 13:25:29 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 13:25:29 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:22:44 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:22:44 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:24:35 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:24:35 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:25:06 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:25:06 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:25:38 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:25:38 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:25:40 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:25:40 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:26:54 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:26:54 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:27:49 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:27:49 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:32:17 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:32:17 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:38:06 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-07 17:38:29 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:38:29 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:39:19 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:39:19 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:41:09 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:41:09 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:41:36 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:41:36 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:47:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:47:14 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:48:28 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:48:28 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:49:26 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:49:26 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:49:53 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:49:53 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:53:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:53:41 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:54:18 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:54:18 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:56:07 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:56:07 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:57:12 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:57:12 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 17:59:51 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 17:59:51 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 18:00:40 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 18:00:40 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 18:02:27 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 18:02:27 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 18:05:38 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 18:05:38 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 18:10:10 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:10:23 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1108): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): DboSource->read(Object(AppModel), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#10 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#11 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2019-05-07 18:11:42 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1108): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): DboSource->read(Object(AppModel), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#10 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#11 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2019-05-07 18:12:01 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1108): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): DboSource->read(Object(AppModel), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#10 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#11 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2019-05-07 18:12:12 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1108): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): DboSource->read(Object(AppModel), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#10 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#11 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2019-05-07 18:13:18 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `User`.`...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1108): DboSource->fetchAll('SELECT `User`.`...', Array)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): DboSource->read(Object(AppModel), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#10 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#11 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2019-05-07 18:14:17 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Model.php(3617): ConnectionManager::getDataSource('default')
#3 /var/www/html/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3644): Model->setSource('users')
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): Model->getDataSource()
#6 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#10 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#11 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#12 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#13 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#16 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
2019-05-07 18:15:12 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 18:15:12 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 18:15:15 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'\'@\'localhost\' (using password: YES)',
  'enabled' => true,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Model.php(3617): ConnectionManager::getDataSource('default')
#3 /var/www/html/cakephp/lib/Cake/Model/Model.php(1155): Model->setDataSource('default')
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3644): Model->setSource('users')
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(3022): Model->getDataSource()
#6 /var/www/html/cakephp/lib/Cake/Model/Model.php(2994): Model->_readDataSource('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(129): Model->find('first', Array)
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BasicAuthenticate.php(91): BaseAuthenticate->_findUser('root', 'password')
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(690): BasicAuthenticate->getUser(Object(CakeRequest))
#10 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(304): AuthComponent->_getUser()
#11 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#12 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#13 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#15 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#16 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}
2019-05-07 18:15:54 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:16:03 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:16:08 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:16:17 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:16:28 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 18:16:36 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:31:37 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:31:37 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:34:44 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:34:56 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:35:50 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:35:54 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:36:25 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:36:27 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:37:51 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:37:51 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:37:58 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:38:37 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:38:37 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:40:02 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:40:02 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:40:53 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:41:20 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 21:41:35 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:41:35 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:41:50 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:41:50 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:42:18 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:42:18 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:42:29 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:42:29 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:46:20 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:46:20 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 21:52:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 21:52:41 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:20:13 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:20:13 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:21:45 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:21:45 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:24:06 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:24:06 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:25:35 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:25:35 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:25:36 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:25:36 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:27:08 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:27:08 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 22:29:45 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown in [/var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php, line 116]
2019-05-07 22:29:45 Error: [FatalErrorException] Uncaught TypeError: Argument 1 passed to ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php:116
Stack trace:
#0 [internal function]: ErrorHandler::handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(1, 'Uncaught TypeEr...', '/var/www/html/c...', 116, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 23:18:53 Error: [MissingActionException] Action PostController::1() could not be found.
Exception Attributes: array (
  'controller' => 'PostController',
  'action' => '1',
)
Request URL: /cakephp/post/1
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2019-05-07 23:25:14 Error: Fatal Error (64): Cannot redeclare UsersController::edit() in [/var/www/html/cakephp/app/Controller/UsersController.php, line 112]
2019-05-07 23:25:14 Error: [FatalErrorException] Cannot redeclare UsersController::edit()
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/var/www/html/c...', 112)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(64, 'Cannot redeclar...', '/var/www/html/c...', 112, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 23:25:29 Error: Fatal Error (64): Cannot redeclare UsersController::edit() in [/var/www/html/cakephp/app/Controller/UsersController.php, line 112]
2019-05-07 23:25:29 Error: [FatalErrorException] Cannot redeclare UsersController::edit()
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/var/www/html/c...', 112)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(64, 'Cannot redeclar...', '/var/www/html/c...', 112, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 23:26:15 Error: Fatal Error (64): Cannot redeclare UsersController::edit() in [/var/www/html/cakephp/app/Controller/UsersController.php, line 112]
2019-05-07 23:26:15 Error: [FatalErrorException] Cannot redeclare UsersController::edit()
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', '/var/www/html/c...', 112)
#1 /var/www/html/cakephp/lib/Cake/Core/App.php(933): ErrorHandler::handleError(64, 'Cannot redeclar...', '/var/www/html/c...', 112, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2019-05-07 23:26:44 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:29:20 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:29:44 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:31:49 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:31:54 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:37:02 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:38:59 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:39:03 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:48:49 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:48:57 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:49:18 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:49:21 Error: [UnauthorizedException] Unauthorized
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(349): BasicAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(UsersController))
#2 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(UsersController))
#3 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#7 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2019-05-07 23:51:54 Error: [MissingViewException] View file "Post/rud_post.ctp" is missing.
Exception Attributes: array (
  'file' => 'Post/rud_post.ctp',
)
Request URL: /cakephp/post/1
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Post/rud_post')
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-07 23:52:50 Error: [MissingViewException] View file "Post/rud_post.ctp" is missing.
Exception Attributes: array (
  'file' => 'Post/rud_post.ctp',
)
Request URL: /cakephp/post/5
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Post/rud_post')
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-07 23:53:15 Error: [MissingViewException] View file "Post/rud_post.ctp" is missing.
Exception Attributes: array (
  'file' => 'Post/rud_post.ctp',
)
Request URL: /cakephp/post/5
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Post/rud_post')
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-07 23:54:32 Error: [MissingViewException] View file "Post/rud_post.ctp" is missing.
Exception Attributes: array (
  'file' => 'Post/rud_post.ctp',
)
Request URL: /cakephp/post/5
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName('Post/rud_post')
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(960): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:36:31 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:37:29 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:37:59 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:39:49 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:40:00 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:40:12 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/register
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:41:27 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/register
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:47:22 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/register
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:50:15 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/register
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:53:09 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:53:13 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:54:05 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:56:27 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 00:56:41 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/posts
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:57:10 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:57:37 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:57:57 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/1
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:58:40 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/1
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 00:58:53 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/1
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 01:00:36 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/5
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 01:01:04 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/8
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 01:01:34 Error: [MissingComponentException] Component class authenticateComponent could not be found.
Exception Attributes: array (
  'class' => 'authenticateComponent',
  'plugin' => false,
)
Request URL: /cakephp/post/8
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/ComponentCollection.php(53): ComponentCollection->load('authenticate', Array)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(643): ComponentCollection->init(Object(PostController))
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(188): Controller->constructClasses()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2019-05-08 01:03:24 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user/7
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:04:10 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user/1
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:09:02 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user/1
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:10:57 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user/1
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:22:51 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /cakephp/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:24:03 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /cakephp/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:24:26 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:25:48 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2019-05-08 01:30:02 Error: [MissingControllerException] Controller class RegisterController could not be found.
Exception Attributes: array (
  'class' => 'RegisterController',
  'plugin' => NULL,
)
Request URL: /cakephp/register
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(117): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
